### ISSUE TITLE
<option name="charting.axisY">numeric</option> is not supported with HTML5

### ISSUE THREAD

**Issue by petterik** [splunk/splunk-app-splunkgit#4]
Did: Went to look at the multi-git//repositories view on my iPad
Expected: Everything to be viewed since Splunk 4.3 is not flash anymore.
Happened: Did not see any of the graphs.

What to do:
Remove <option name="charting.axisY">numeric</option> from the views, since it's not HTML5 supported. Splunk then rollsback to a flash view instead.

**Comment by emreberge** [comment]
Confirmed that the _multi repositories_ now work on ipad, but the following views still need flash:
- Git/Repository
- Git/Files
- Github/Repo statistics

**Comment by emreberge** [comment]
Created issues for each one closing this one.
- Git/Repository, #7
- Git/Files, #8 
- Github/Repo, #9
